### ISSUE TITLE
Offset update cache

### ISSUE THREAD

**Issue by eskan** [sporritt/jsPlumb#402]
Hi,
i've an offset issue when i create .. delete .. create again an element with the same id in different place (offset). Only the first creation offset is kept.
I've seen you use a sizes array, an offsets and offsetTimestamps objects and they aren't reset/clean with jsPlumb.deleteEveryEndpoint() or when a element is removed.

For now i've just add : 
        offsets = {};
        offsetTimestamps = {};

to jsPlumb.deleteEveryEndpoint() and offset are calculate and good.
I use the 1.7.6_alpha release
Regards,
Cyrille

**Comment by jrock125** [comment]
In fact even jsPlumb.reset() doesn't clear offsets. 
So if element with the same ID is recreated in a different place - even after complete reset endpoints and connections will be drawn at/to the element former place. 
I am seeing it with 1.7.5

**Comment by sporritt** [comment]
fixed in 1.7.6 dev

**Comment by alexyaseen** [comment]
I'm still running into this (or a similar) problem in 1.7.10:

1. start with an element with an endpoint attached
2. delete that element manually
3. delete the endpoint using deleteEndpoint(endpoint)
4. add new element with same ID as original
5. try to add an endpoint to the new element. It ends up floating in space near the top of the document

I'm relatively tied to using this workflow. Any ideas on how I can make this work?

**Comment by cdaniel** [comment]
I'm experiencing this, too.

**Comment by sporritt** [comment]
on which version, @cdaniel ?

**Comment by cdaniel** [comment]
2.4.2 :-) I would not complain if I was not using the latest one. I have implemented diff for certain graphs, which shows previous state:
Diff enabled:
![screen shot 2017-06-19 at 12 09 25](https://user-images.githubusercontent.com/1265262/27280501-6c2ac4d8-54e8-11e7-8279-5627ee997858.png)
Diff disabled (old nodes removed outside of jsPlumb):
![screen shot 2017-06-19 at 12 09 32](https://user-images.githubusercontent.com/1265262/27280509-74a2a59a-54e8-11e7-9f4a-803ce6f0c581.png)
Diff enabled again (node readded outside of jsplumb, note mislocated endpoint):
![screen shot 2017-06-19 at 12 09 38](https://user-images.githubusercontent.com/1265262/27280522-7c4b0ddc-54e8-11e7-8d68-42747cc23904.png)

**Comment by maogongzi** [comment]
I've met with the same issue and used an Ad-hoc solution which is rather easy to implement: everytime after a node is inserted into the flow I'll give it a DOM id with a random uuid inside it:

```
    // convert a node id in Number type into an unique DOM #id
    getNodeStrId(node) {
      // uuid: use whatever algorithm you like to generate a uuid, I googled one.
      return `flow-node-${node.uuid}-${node.id}`;
    },
```

to parse the original id just `split("-")` and `pop()`

Still looking forward to the official solution on this, but for people struggling on it, it might be a temporary solution easy to accomplish, :)

**Comment by AdamJessop** [comment]
Still seeing this issue also, dynamically moving the original node then deleting / recreating it's endpoints doesn't clear the offset cache and causes issues.

**Comment by AdamJessop** [comment]
See a codepen of the issue:
https://codepen.io/AdamJessop/pen/qBBYxEK
